version: '3.8'
services:
  spring-app:
    image: a951b78d5e0e
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: springappdb
    ports:
      - "3307:3306"